package:
	if not exist ".\build" mkdir .\build
	del /f .\build\acolyte.oxt
	cd .\acolyte\ && 7za a -tzip ..\build\acolyte.oxt * -xr!*.DS_Store -xr!*.git* -xr!*__pycache__* -xr!*.pyc -xr!*.pyo -xr!*.pyd -xr!*.pyo -xr!*.pyw -xr!*.py~ -xr!*.swp -xr!*.swo -xr!*.swn -xr!*.swo -xr!*.md